name: Deploy to WebLogic

on:
  workflow_call:
    inputs:
      server_host:
        description: "URL o IP del servidor WebLogic"
        required: true
        type: string
      server_port:
        description: "Puerto del servidor WebLogic"
        required: true
        type: string
      weblogic_user:
        description: "Usuario con permisos de despliegue"
        required: true
        type: string
      target_name:
        description: "Nombre del target (server, cluster, etc.)"
        required: true
        type: string
      app_name:
        description: "Nombre lógico de la aplicación"
        required: true
        type: string
      artifact_name:
        description: "Nombre del artefacto (EAR) a desplegar"
        required: true
        type: string
    secrets:
      WEBLOGIC_PASSWORD:
        description: "Password del usuario WebLogic"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: ear-artifact  # Este es el nombre que usamos en actions/upload-artifact en la funcion de buildAnt.yml

      - name: Verificar contenido descargado
        run: ls -l

      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip unzip
          pip3 install --upgrade wlsdeploy

      - name: Desplegar aplicación a WebLogic
        env:
          WLS_USER: ${{ inputs.weblogic_user }}
          WLS_PASS: ${{ secrets.WEBLOGIC_PASSWORD }}
          WLS_HOST: ${{ inputs.server_host }}
          WLS_PORT: ${{ inputs.server_port }}
          WLS_TARGET: ${{ inputs.target_name }}
          WLS_APP: ${{ inputs.app_name }}
        run: |
          EAR_FILE=$(ls *.ear | head -n 1)
          echo "Desplegando $EAR_FILE a WebLogic..."

          java weblogic.Deployer \
            -adminurl t3://${WLS_HOST}:${WLS_PORT} \
            -username $WLS_USER \
            -password $WLS_PASS \
            -deploy $EAR_FILE \
            -targets $WLS_TARGET \
            -name $WLS_APP \
            -upload
