name: Deploy to WebLogic

on:
  workflow_call:
    inputs:
      artifacts_pattern:
        description: 'Directorio o expresión regular que describe qué se desea almacenar como artefacto'
        required: true
        default: 'build/ear/*ear'
        type: string
      artifacts_name:
        description: 'Nombre del Ear'
        required: true
        default: 'HelloWorld'
        type: string
      server_host:
        description: "URL o IP del servidor WebLogic"
        required: true
        type: string
      server_port:
        description: "Puerto del servidor WebLogic"
        required: true
        type: string
      weblogic_user:
        description: "Usuario con permisos de despliegue"
        required: true
        type: string
      target_name:
        description: "Nombre del target (server, cluster, etc.)"
        required: true
        type: string
      app_name:
        description: "Nombre lógico de la aplicación"
        required: true
        type: string
      artifact_name:
        description: "Nombre del artefacto (EAR) a desplegar"
        required: true
        type: string
    secrets:
      WEBLOGIC_PASSWORD:
        description: "Password del usuario WebLogic"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: ear-artifact
          path: downloaded-ear

      - name: Verificar artefacto
        run: |
          ls -lh downloaded-ear/
          echo "EAR listo para despliegue: $(ls downloaded-ear/*.ear)"